#!/bin/bash

PREFIX=$HOME/opt/redis
VERSION=2.6.2
NAME=redis-$VERSION

cd  $HOME/tmp
if [ ! -e $NAME.tar.gz ]; then
    wget http://redis.googlecode.com/files/$NAME.tar.gz
fi
tar xzf $NAME.tar.gz
cd $NAME
make
make PREFIX=$PREFIX install
ln -s $PREFIX/bin/redis-server ~/bin/
mkdir $HOME/var/redis
