#!/bin/bash

PREFIX=$HOME/opt/boost

cd  ~/tmp
if [ ! -e boost_1_48_0.tar.gz ]; then
    wget http://heanet.dl.sourceforge.net/project/boost/boost/1.48.0/boost_1_48_0.tar.gz
fi
tar xzf boost_1_48_0.tar.gz
cd boost_1_48_0
#./configure --prefix=$PREFIX
#make
#make install
