#!/bin/bash

PREFIX=$HOME/opt/postgresql
VERSION=9.2.1

cd  ~/tmp
if [ ! -e 'postgresql-$VERSION.tar.gz' ]; then
    wget http://ftp.postgresql.org/pub/source/v$VERSION/postgresql-$VERSION.tar.gz
fi
tar xzf postgresql-$VERSION.tar.gz
cd postgresql-$VERSION
./configure --prefix=$PREFIX
make
make install
cd $PREFIX
./bin/initdb -D data --locale=sv_SE.UTF-8
cd data

# just make them so they are not confused with the real configs
cp postgresql.conf postgresql.conf.default
cp pg_hba.conf pg_hba.conf.default
cp pg_ident.conf pg_ident.conf.default

if [ ! -d $HOME/bin ]; then
    mkdir $HOME/bin
fi

for cmd in 'createdb' 'dropdb' 'createuser' 'dropuser' 'pg_dump' 'pg_restore' 'psql'
do
    echo "#!/bin/bash

$PREFIX/bin/$cmd \"\$@\" -h $HOME/run" > ~/bin/$cmd
    chmod 700 $HOME/bin/$cmd
done

ln -s $PREFIX/bin/pg_config $HOME/bin/
