#!/bin/bash

chmod 700 ~/

if [ ! -d $HOME/.ssh ]; then
    mkdir $HOME/.ssh
fi
chmod 700 $HOME/.ssh
touch $HOME/.ssh/authorized_keys
if [ `cat $HOME/.ssh/config | grep -c "Host *.aino.se"` -eq 0 ]; then
    echo "Host *.aino.se
    port 24" >> $HOME/.ssh/config
fi
if [ ! -e $HOME/.ssh/id_dsa ]; then
    ssh-keygen -t dsa
fi
chmod 600 $HOME/.ssh/*


if [[ $HOSTNAME ==  *webfaction* ]]; then
    mkdir -p $HOME/lib/python2.7
    easy_install-2.7 pip
fi

function pyinstall {
    PACKAGE=$1
    VERSION=$2
    NAME=$PACKAGE-$VERSION
    cd $HOME/tmp
    if [ ! -e $NAME.tar.gz ]; then
        wget http://pypi.python.org/packages/source/${PACKAGE:0:1}/$PACKAGE/$NAME.tar.gz
    fi
    tar xzf $NAME.tar.gz
    cd $NAME
    python2.7 setup.py build && python2.7 setup.py install
} 


pyinstall virtualenv 1.8.2
pyinstall virtualenvwrapper 3.6
pyinstall supervisor 3.0b1


if [ `cat $HOME/.bashrc | grep -c virtualenvwrapper` -eq 0 ]; then
    if [[ $HOSTNAME ==  *webfaction* ]]; then
        CONF="\nexport VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2.7"
    fi
    CONF="$CONF\nsource `which virtualenvwrapper.sh`\nexport PATH=~/bin:~/.local/bin:\$PATH"
    echo -e $CONF >> $HOME/.bashrc
fi

echo "Execute: source ~/.bashrc"

