#!/bin/bash

chmod 700 ~/

if [ ! -d $HOME/.ssh ]; then
    mkdir $HOME/.ssh
fi
chmod 700 $HOME/.ssh
touch $HOME/.ssh/authorized_keys
if [ `cat $HOME/.ssh/config | grep -c "Host *.aino.se"` -eq 0 ]; then
    echo "Host *.aino.se
    port 24" >> $HOME/.ssh/config
fi
if [ ! -e $HOME/.ssh/id_dsa ]; then
    ssh-keygen -t dsa
fi
chmod 600 $HOME/.ssh/*


if [[ $HOSTNAME ==  *webfaction* ]]; then
    mkdir -p $HOME/lib/python2.7
fi


easy_install-2.7 pip

freeze=`pip freeze`
if [ `echo $freeze | grep -c virtualenv\=\=` -eq 0 ]; then
    `pip install --user virtualenv`
fi
if [ `echo $freeze | grep -c virtualenvwrapper\=\=` -eq 0 ]; then
    `pip install --user virtualenvwrapper`
fi
if [ `echo $freeze | grep -c supervisor\=\=` -eq 0 ]; then
    `pip install --user supervisor`
fi
 

if [ `cat $HOME/.bashrc | grep -c virtualenvwrapper` -eq 0 ]; then
    if [[ $HOSTNAME ==  *webfaction* ]]; then
        CONF="\nexport VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2.7"
    fi
    CONF="$CONF\nsource `which virtualenvwrapper.sh`\nexport PATH=~/bin:~/bin/.local/bin:\$PATH"
    echo -e $CONF >> $HOME/.bashrc
fi

echo "Execute: source ~/.bashrc"

