#!/bin/bash

LIBEVENT_PREFIX=$HOME/opt/libevent
LIBEVENT_VERSION=2.0.19
MEMCACHED_PREFIX=$HOME/opt/memcached
MEMCACHED_VERSION=1.4.13



cd  ~/tmp
if [ ! -e libevent-$LIBEVENT_VERSION-stable.tar.gz ]; then
    wget https://github.com/downloads/libevent/libevent/libevent-$LIBEVENT_VERSION-stable.tar.gz
fi
tar xzf libevent-$LIBEVENT_VERSION-stable.tar.gz
cd libevent-$LIBEVENT_VERSION-stable
./configure --prefix=$LIBEVENT_PREFIX && make && make install

if [ ! -e memcached-$MEMCACHED_VERSION.tar.gz ]; then
    wget http://memcached.googlecode.com/files/memcached-$MEMCACHED_VERSION.tar.gz
fi
tar xvzf memcached-$MEMCACHED_VERSION.tar.gz
cd memcached-$MEMCACHED_VERSION/
./configure --prefix=$MEMCACHED_PREFIX --with-libevent=$LIBEVENT_PREFIX && make && make install
ln -s $MEMCACHED_PREFIX/bin/memcached $HOME/bin/
