#!/bin/bash


DATA=$HOME/var/redis
RUN=$HOME/run
CONF=$HOME/etc/redis.conf


if [ ! -d $DATA ]; then 
    mkdir -p $DATA
fi

echo -n "What port? "
read PORT

rm $CONF

while read line
do
    L=`eval echo "$line"`
    if [ "$L" ]; then
        echo $L >> $CONF
    fi
done < "$(dirname $0)/redis.conf"
