#!/bin/bash

CRON=$HOME/tmp/cron
crontab -l > $CRON

elif [ `cat $CRON | grep -c monit` -ne 0 ]; then
    echo "Error: crontab already contains monit."
    exit 1
fi

echo "*/5 * * * *		$HOME/opt/monit/bin/monit -c$HOME/etc/monitrc" >> $CRON
crontab $CRON

