#!/bin/bash

ETC=$HOME/etc
CONF=$ETC/supervisord.conf
LOG=$HOME/log
PREFIX=$HOME/opt
SECTION="program:postgresql"


if [ ! -e $CONF ]; then
    echo "Error: $CONF does not exist."
    exit 1
elif [ `cat $CONF | grep -c $SECTION` -ne 0 ]; then
    echo "Error: $CONF already contains a $SECTION section."
    exit 1
fi

echo "
[$SECTION]
command=$PREFIX/postgresql/bin/postgres -c config_file=$ETC/postgresql.conf
stdout_logfile=$LOG/postgresql.log
autorestart=true
redirect_stderr=true
stopsignal=INT" >> $CONF
